<a href="https://colab.research.google.com/github/dhruv0050/Pytorch/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A tensor is simply a generalized form of data used in deep learning to store and process information.

Why are Tensors Needed in Deep Learning?
Deep learning works with complex data:
 - Images
 - Text
 - Audio
 - Video
 - Sensor data

All of these naturally require multiple dimensions, and tensors are the most efficient way to handle them.

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.get_device_name(0))
else:
  print("GPU is not available")

GPU is available
Tesla T4


### **Creating a Tensor**

In [4]:
# Using empty
torch.empty(2,3)

tensor([[8.9365e-11, 0.0000e+00, 1.5456e-42],
        [0.0000e+00, 8.9364e-11, 0.0000e+00]])

In [5]:
# Using zeros/ones
torch.ones(4,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using random entries
torch.rand(5,9)

tensor([[0.0563, 0.7489, 0.9001, 0.5220, 0.9135, 0.5636, 0.7503, 0.8117, 0.1417],
        [0.7183, 0.6724, 0.4067, 0.3571, 0.9330, 0.7180, 0.2959, 0.7464, 0.0779],
        [0.4206, 0.2960, 0.2435, 0.7038, 0.3498, 0.6552, 0.6519, 0.8483, 0.8034],
        [0.5700, 0.9276, 0.9128, 0.7376, 0.3510, 0.3298, 0.4740, 0.3119, 0.5331],
        [0.7965, 0.4418, 0.4177, 0.9345, 0.1454, 0.7071, 0.5000, 0.1452, 0.3599]])

In [8]:
# Custom Tensor
torch.tensor([12,2,3])

tensor([12,  2,  3])

### **Tensor Datatypes**

In [9]:
x = torch.rand(4,5)
x

tensor([[9.6970e-01, 4.2340e-01, 3.4094e-01, 2.9451e-01, 5.7411e-01],
        [1.5900e-01, 8.1946e-01, 1.0119e-01, 8.7685e-01, 5.3112e-01],
        [2.5133e-01, 5.5353e-01, 6.1023e-04, 7.6883e-01, 4.2427e-01],
        [8.1888e-01, 4.9477e-01, 8.9851e-01, 2.0762e-01, 8.1920e-01]])

In [10]:
x.dtype

torch.float32

In [11]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [12]:
x.to(torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

### **Mathematical Operations on tensors**

In [27]:
x = torch.rand(2,3)
y = torch.rand(2,3)
z = torch.rand(3,2)
k = torch.rand(4,4)

In [28]:
x

tensor([[0.9394, 0.2355, 0.6390],
        [0.2400, 0.8994, 0.6292]])

In [29]:
x + 2

tensor([[2.9394, 2.2355, 2.6390],
        [2.2400, 2.8994, 2.6292]])

In [30]:
x**2

tensor([[0.8825, 0.0555, 0.4083],
        [0.0576, 0.8090, 0.3959]])

In [31]:
# Matrix Multiplication
torch.matmul(x,z)

tensor([[0.9403, 0.8798],
        [1.0816, 0.6728]])

In [33]:
# Determinant of a Matrix
torch.det(k)

tensor(-0.1053)

In [38]:
# Comparisons

print(x > y)
print(x >= y)
print(x <= y)
print(x == y)
print(x != y)

tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


In [39]:
torch.sum(x)

tensor(3.5825)

In [40]:
torch.max(y)

tensor(0.8252)

In [41]:
torch.argmax(y)

tensor(3)

In [42]:
torch.log(x)

tensor([[-0.0625, -1.4460, -0.4479],
        [-1.4270, -0.1060, -0.4633]])

In [43]:
torch.sigmoid(x)

tensor([[0.7190, 0.5586, 0.6545],
        [0.5597, 0.7108, 0.6523]])

In [44]:
torch.relu(k)

tensor([[0.0858, 0.5325, 0.4339, 0.3732],
        [0.8626, 0.7211, 0.2898, 0.6183],
        [0.6273, 0.2168, 0.2352, 0.0387],
        [0.4916, 0.1938, 0.1907, 0.9547]])

In [47]:
x = x + y

In [48]:
x

tensor([[1.6911, 0.7635, 0.8856],
        [1.0652, 0.9075, 0.8808]])